// $Module: sec_fab_firewall $
// $RegisterBank Version: V 1.0.00 $
// $Author: Sean.Lin $
// $Date: Thu, 18 Apr 2019 10:46:34 AM $
//

//GEN REG ADDR/OFFSET/MASK
#define  SEC_FAB_FIREWALL_REG_FAB_FW_CTRL  0x0
#define  sec_fab_firewall_fabFW_hsperi_m_ar_ns  0x4
#define  sec_fab_firewall_fabFW_hsperi_m_aw_ns  0x8
#define  sec_fab_firewall_fabFW_hsperi_s_tz_s  0xc
#define  sec_fab_firewall_reg_hsperi_fw_tz_s  0x10
#define  sec_fab_firewall_fabFW_ddr_m_ar_ns  0x14
#define  sec_fab_firewall_fabFW_ddr_m_aw_ns  0x18
#define  sec_fab_firewall_fabFW_ddr_ctrl_s_tz_s  0x1c
#define  sec_fab_firewall_reg_sram_m_ar_ns  0x20
#define  sec_fab_firewall_reg_sram_m_aw_ns  0x24
#define  sec_fab_firewall_reg_sram_s_tz_s  0x28
#define  sec_fab_firewall_fabFW_ap_s4_tz_s  0x30
#define  sec_fab_firewall_fabFW_tpu0_m_ar_ns  0x34
#define  sec_fab_firewall_fabFW_tpu0_m_aw_ns  0x38
#define  sec_fab_firewall_fabFW_tpu0_s_tz_s  0x3c
#define  sec_fab_firewall_fabFW_top_s_tz_s  0x50
#define  sec_fab_firewall_reg_peri_fw_s_tz_s  0x54
#define  sec_fab_firewall_reg_rom_fw_s_tz_s  0x58
#define  sec_fab_firewall_fabFW_ROM_psmsk  0x5c
//#define  sec_fab_firewall_reg_fab_fw_ctrl   0x0
#define  SEC_FAB_FIREWALL_REG_FAB_FW_CTRL_OFFSET 0
#define  SEC_FAB_FIREWALL_REG_FAB_FW_CTRL_MASK   0xffffffff
#define  sec_fab_firewall_fabFW_hsperi_m0_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m0_ar_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_hsperi_m0_ar_ns_MASK   0x1
#define  SEC_FAB_FIREWALL_FABFW_HSPERI_M1_AR_NS   0x4
#define  SEC_FAB_FIREWALL_FABFW_HSPERI_M1_AR_NS_OFFSET 1
#define  SEC_FAB_FIREWALL_FABFW_HSPERI_M1_AR_NS_MASK   0x2
#define  sec_fab_firewall_fabFW_hsperi_m2_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m2_ar_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_hsperi_m2_ar_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_hsperi_m3_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m3_ar_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_hsperi_m3_ar_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_hsperi_m4_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m4_ar_ns_OFFSET 4
#define  sec_fab_firewall_fabFW_hsperi_m4_ar_ns_MASK   0x10
#define  sec_fab_firewall_fabFW_hsperi_m5_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m5_ar_ns_OFFSET 5
#define  sec_fab_firewall_fabFW_hsperi_m5_ar_ns_MASK   0x20
#define  sec_fab_firewall_fabFW_hsperi_m6_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m6_ar_ns_OFFSET 6
#define  sec_fab_firewall_fabFW_hsperi_m6_ar_ns_MASK   0x40
#define  sec_fab_firewall_fabFW_hsperi_m7_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m7_ar_ns_OFFSET 7
#define  sec_fab_firewall_fabFW_hsperi_m7_ar_ns_MASK   0x80
#define  sec_fab_firewall_fabFW_hsperi_m8_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m8_ar_ns_OFFSET 8
#define  sec_fab_firewall_fabFW_hsperi_m8_ar_ns_MASK   0x100
#define  sec_fab_firewall_fabFW_hsperi_m9_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m9_ar_ns_OFFSET 9
#define  sec_fab_firewall_fabFW_hsperi_m9_ar_ns_MASK   0x200
#define  sec_fab_firewall_fabFW_hsperi_m10_ar_ns   0x4
#define  sec_fab_firewall_fabFW_hsperi_m10_ar_ns_OFFSET 10
#define  sec_fab_firewall_fabFW_hsperi_m10_ar_ns_MASK   0x400
#define  sec_fab_firewall_fabFW_hsperi_m0_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m0_aw_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_hsperi_m0_aw_ns_MASK   0x1
#define  sec_fab_firewall_fabFW_hsperi_m1_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m1_aw_ns_OFFSET 1
#define  sec_fab_firewall_fabFW_hsperi_m1_aw_ns_MASK   0x2
#define  sec_fab_firewall_fabFW_hsperi_m2_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m2_aw_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_hsperi_m2_aw_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_hsperi_m3_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m3_aw_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_hsperi_m3_aw_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_hsperi_m4_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m4_aw_ns_OFFSET 4
#define  sec_fab_firewall_fabFW_hsperi_m4_aw_ns_MASK   0x10
#define  sec_fab_firewall_fabFW_hsperi_m5_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m5_aw_ns_OFFSET 5
#define  sec_fab_firewall_fabFW_hsperi_m5_aw_ns_MASK   0x20
#define  sec_fab_firewall_fabFW_hsperi_m6_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m6_aw_ns_OFFSET 6
#define  sec_fab_firewall_fabFW_hsperi_m6_aw_ns_MASK   0x40
#define  sec_fab_firewall_fabFW_hsperi_m7_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m7_aw_ns_OFFSET 7
#define  sec_fab_firewall_fabFW_hsperi_m7_aw_ns_MASK   0x80
#define  sec_fab_firewall_fabFW_hsperi_m8_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m8_aw_ns_OFFSET 8
#define  sec_fab_firewall_fabFW_hsperi_m8_aw_ns_MASK   0x100
#define  sec_fab_firewall_fabFW_hsperi_m9_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m9_aw_ns_OFFSET 9
#define  sec_fab_firewall_fabFW_hsperi_m9_aw_ns_MASK   0x200
#define  sec_fab_firewall_fabFW_hsperi_m10_aw_ns   0x8
#define  sec_fab_firewall_fabFW_hsperi_m10_aw_ns_OFFSET 10
#define  sec_fab_firewall_fabFW_hsperi_m10_aw_ns_MASK   0x400
#define  sec_fab_firewall_fabFW_hsperi_s0_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s0_tz_s_OFFSET 0
#define  sec_fab_firewall_fabFW_hsperi_s0_tz_s_MASK   0x1
#define  sec_fab_firewall_fabFW_hsperi_s1_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s1_tz_s_OFFSET 1
#define  sec_fab_firewall_fabFW_hsperi_s1_tz_s_MASK   0x2
#define  sec_fab_firewall_fabFW_hsperi_s2_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s2_tz_s_OFFSET 2
#define  sec_fab_firewall_fabFW_hsperi_s2_tz_s_MASK   0x4
#define  sec_fab_firewall_fabFW_hsperi_s3_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s3_tz_s_OFFSET 3
#define  sec_fab_firewall_fabFW_hsperi_s3_tz_s_MASK   0x8
#define  sec_fab_firewall_fabFW_hsperi_s4_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s4_tz_s_OFFSET 4
#define  sec_fab_firewall_fabFW_hsperi_s4_tz_s_MASK   0x10
#define  sec_fab_firewall_fabFW_hsperi_s5_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s5_tz_s_OFFSET 5
#define  sec_fab_firewall_fabFW_hsperi_s5_tz_s_MASK   0x20
#define  sec_fab_firewall_fabFW_hsperi_s6_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s6_tz_s_OFFSET 6
#define  sec_fab_firewall_fabFW_hsperi_s6_tz_s_MASK   0x40
#define  sec_fab_firewall_fabFW_hsperi_s7_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s7_tz_s_OFFSET 7
#define  sec_fab_firewall_fabFW_hsperi_s7_tz_s_MASK   0x80
#define  sec_fab_firewall_fabFW_hsperi_s8_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s8_tz_s_OFFSET 8
#define  sec_fab_firewall_fabFW_hsperi_s8_tz_s_MASK   0x100
#define  sec_fab_firewall_fabFW_hsperi_s9_tz_s   0xc
#define  sec_fab_firewall_fabFW_hsperi_s9_tz_s_OFFSET 9
#define  sec_fab_firewall_fabFW_hsperi_s9_tz_s_MASK   0x200
#define  sec_fab_firewall_reg_hsperi_fw_tz_s   0x10
#define  sec_fab_firewall_reg_hsperi_fw_tz_s_OFFSET 0
#define  sec_fab_firewall_reg_hsperi_fw_tz_s_MASK   0xffffffff
#define  sec_fab_firewall_fabFW_ddr_m0_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m0_ar_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_ddr_m0_ar_ns_MASK   0x1
#define  sec_fab_firewall_fabFW_ddr_m1_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m1_ar_ns_OFFSET 1
#define  sec_fab_firewall_fabFW_ddr_m1_ar_ns_MASK   0x2
#define  sec_fab_firewall_fabFW_ddr_m2_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m2_ar_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_ddr_m2_ar_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_ddr_m3_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m3_ar_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_ddr_m3_ar_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_ddr_m4_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m4_ar_ns_OFFSET 4
#define  sec_fab_firewall_fabFW_ddr_m4_ar_ns_MASK   0x10
#define  sec_fab_firewall_fabFW_ddr_m5_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m5_ar_ns_OFFSET 5
#define  sec_fab_firewall_fabFW_ddr_m5_ar_ns_MASK   0x20
#define  sec_fab_firewall_fabFW_ddr_m6_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m6_ar_ns_OFFSET 6
#define  sec_fab_firewall_fabFW_ddr_m6_ar_ns_MASK   0x40
#define  sec_fab_firewall_fabFW_ddr_m7_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m7_ar_ns_OFFSET 7
#define  sec_fab_firewall_fabFW_ddr_m7_ar_ns_MASK   0x80
#define  sec_fab_firewall_fabFW_ddr_m8_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m8_ar_ns_OFFSET 8
#define  sec_fab_firewall_fabFW_ddr_m8_ar_ns_MASK   0x100
#define  sec_fab_firewall_fabFW_ddr_m9_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m9_ar_ns_OFFSET 9
#define  sec_fab_firewall_fabFW_ddr_m9_ar_ns_MASK   0x200
#define  sec_fab_firewall_fabFW_ddr_m10_ar_ns   0x14
#define  sec_fab_firewall_fabFW_ddr_m10_ar_ns_OFFSET 10
#define  sec_fab_firewall_fabFW_ddr_m10_ar_ns_MASK   0x400
#define  sec_fab_firewall_fabFW_ddr_m0_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m0_aw_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_ddr_m0_aw_ns_MASK   0x1
#define  sec_fab_firewall_fabFW_ddr_m1_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m1_aw_ns_OFFSET 1
#define  sec_fab_firewall_fabFW_ddr_m1_aw_ns_MASK   0x2
#define  sec_fab_firewall_fabFW_ddr_m2_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m2_aw_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_ddr_m2_aw_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_ddr_m3_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m3_aw_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_ddr_m3_aw_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_ddr_m4_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m4_aw_ns_OFFSET 4
#define  sec_fab_firewall_fabFW_ddr_m4_aw_ns_MASK   0x10
#define  sec_fab_firewall_fabFW_ddr_m5_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m5_aw_ns_OFFSET 5
#define  sec_fab_firewall_fabFW_ddr_m5_aw_ns_MASK   0x20
#define  sec_fab_firewall_fabFW_ddr_m6_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m6_aw_ns_OFFSET 6
#define  sec_fab_firewall_fabFW_ddr_m6_aw_ns_MASK   0x40
#define  sec_fab_firewall_fabFW_ddr_m7_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m7_aw_ns_OFFSET 7
#define  sec_fab_firewall_fabFW_ddr_m7_aw_ns_MASK   0x80
#define  sec_fab_firewall_fabFW_ddr_m8_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m8_aw_ns_OFFSET 8
#define  sec_fab_firewall_fabFW_ddr_m8_aw_ns_MASK   0x100
#define  sec_fab_firewall_fabFW_ddr_m9_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m9_aw_ns_OFFSET 9
#define  sec_fab_firewall_fabFW_ddr_m9_aw_ns_MASK   0x200
#define  sec_fab_firewall_fabFW_ddr_m10_aw_ns   0x18
#define  sec_fab_firewall_fabFW_ddr_m10_aw_ns_OFFSET 10
#define  sec_fab_firewall_fabFW_ddr_m10_aw_ns_MASK   0x400
#define  sec_fab_firewall_fabFW_ddr_ctrl_s0_tz_s   0x1c
#define  sec_fab_firewall_fabFW_ddr_ctrl_s0_tz_s_OFFSET 0
#define  sec_fab_firewall_fabFW_ddr_ctrl_s0_tz_s_MASK   0x1
#define  sec_fab_firewall_fabFW_ddr_ctrl_s1_tz_s   0x1c
#define  sec_fab_firewall_fabFW_ddr_ctrl_s1_tz_s_OFFSET 1
#define  sec_fab_firewall_fabFW_ddr_ctrl_s1_tz_s_MASK   0x2
#define  sec_fab_firewall_fabFW_ddr_ctrl_s2_tz_s   0x1c
#define  sec_fab_firewall_fabFW_ddr_ctrl_s2_tz_s_OFFSET 2
#define  sec_fab_firewall_fabFW_ddr_ctrl_s2_tz_s_MASK   0x4
#define  sec_fab_firewall_fabFW_ddr_ctrl_s3_tz_s   0x1c
#define  sec_fab_firewall_fabFW_ddr_ctrl_s3_tz_s_OFFSET 3
#define  sec_fab_firewall_fabFW_ddr_ctrl_s3_tz_s_MASK   0x8
#define  sec_fab_firewall_reg_sram_m_ar_ns   0x20
#define  sec_fab_firewall_reg_sram_m_ar_ns_OFFSET 0
#define  sec_fab_firewall_reg_sram_m_ar_ns_MASK   0x1
#define  sec_fab_firewall_reg_sram_m_aw_ns   0x24
#define  sec_fab_firewall_reg_sram_m_aw_ns_OFFSET 0
#define  sec_fab_firewall_reg_sram_m_aw_ns_MASK   0x1
#define  SEC_FAB_FIREWALL_REG_SRAM_S_TZ_S   0x28
#define  sec_fab_firewall_reg_sram_s_tz_s_OFFSET 0
#define  sec_fab_firewall_reg_sram_s_tz_s_MASK   0xffffffff
#define  sec_fab_firewall_fabFW_ap_s4_tz_s   0x30
#define  sec_fab_firewall_fabFW_ap_s4_tz_s_OFFSET 4
#define  sec_fab_firewall_fabFW_ap_s4_tz_s_MASK   0x10
#define  sec_fab_firewall_fabFW_tpu0_m0_ar_ns   0x34
#define  sec_fab_firewall_fabFW_tpu0_m0_ar_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_tpu0_m0_ar_ns_MASK   0x1
#define  sec_fab_firewall_fabFW_tpu0_m1_ar_ns   0x34
#define  sec_fab_firewall_fabFW_tpu0_m1_ar_ns_OFFSET 1
#define  sec_fab_firewall_fabFW_tpu0_m1_ar_ns_MASK   0x2
#define  sec_fab_firewall_fabFW_tpu0_m2_ar_ns   0x34
#define  sec_fab_firewall_fabFW_tpu0_m2_ar_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_tpu0_m2_ar_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_tpu0_m3_ar_ns   0x34
#define  sec_fab_firewall_fabFW_tpu0_m3_ar_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_tpu0_m3_ar_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_tpu0_m0_aw_ns   0x38
#define  sec_fab_firewall_fabFW_tpu0_m0_aw_ns_OFFSET 0
#define  sec_fab_firewall_fabFW_tpu0_m0_aw_ns_MASK   0x1
#define  sec_fab_firewall_fabFW_tpu0_m1_aw_ns   0x38
#define  sec_fab_firewall_fabFW_tpu0_m1_aw_ns_OFFSET 1
#define  sec_fab_firewall_fabFW_tpu0_m1_aw_ns_MASK   0x2
#define  sec_fab_firewall_fabFW_tpu0_m2_aw_ns   0x38
#define  sec_fab_firewall_fabFW_tpu0_m2_aw_ns_OFFSET 2
#define  sec_fab_firewall_fabFW_tpu0_m2_aw_ns_MASK   0x4
#define  sec_fab_firewall_fabFW_tpu0_m3_aw_ns   0x38
#define  sec_fab_firewall_fabFW_tpu0_m3_aw_ns_OFFSET 3
#define  sec_fab_firewall_fabFW_tpu0_m3_aw_ns_MASK   0x8
#define  sec_fab_firewall_fabFW_tpu0_s0_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s0_tz_s_OFFSET 0
#define  sec_fab_firewall_fabFW_tpu0_s0_tz_s_MASK   0x1
#define  sec_fab_firewall_fabFW_tpu0_s1_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s1_tz_s_OFFSET 1
#define  sec_fab_firewall_fabFW_tpu0_s1_tz_s_MASK   0x2
#define  sec_fab_firewall_fabFW_tpu0_s2_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s2_tz_s_OFFSET 2
#define  sec_fab_firewall_fabFW_tpu0_s2_tz_s_MASK   0x4
#define  sec_fab_firewall_fabFW_tpu0_s3_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s3_tz_s_OFFSET 3
#define  sec_fab_firewall_fabFW_tpu0_s3_tz_s_MASK   0x8
#define  sec_fab_firewall_fabFW_tpu0_s4_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s4_tz_s_OFFSET 4
#define  sec_fab_firewall_fabFW_tpu0_s4_tz_s_MASK   0x10
#define  sec_fab_firewall_fabFW_tpu0_s5_tz_s   0x3c
#define  sec_fab_firewall_fabFW_tpu0_s5_tz_s_OFFSET 5
#define  sec_fab_firewall_fabFW_tpu0_s5_tz_s_MASK   0x20
#define  sec_fab_firewall_fabFW_top_s0_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s0_tz_s_OFFSET 0
#define  sec_fab_firewall_fabFW_top_s0_tz_s_MASK   0x1
#define  sec_fab_firewall_fabFW_top_s1_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s1_tz_s_OFFSET 1
#define  sec_fab_firewall_fabFW_top_s1_tz_s_MASK   0x2
#define  sec_fab_firewall_fabFW_top_s2_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s2_tz_s_OFFSET 2
#define  sec_fab_firewall_fabFW_top_s2_tz_s_MASK   0x4
#define  sec_fab_firewall_fabFW_top_s3_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s3_tz_s_OFFSET 3
#define  sec_fab_firewall_fabFW_top_s3_tz_s_MASK   0x8
#define  sec_fab_firewall_fabFW_top_s4_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s4_tz_s_OFFSET 4
#define  sec_fab_firewall_fabFW_top_s4_tz_s_MASK   0x10
#define  sec_fab_firewall_fabFW_top_s5_tz_s   0x50
#define  sec_fab_firewall_fabFW_top_s5_tz_s_OFFSET 5
#define  sec_fab_firewall_fabFW_top_s5_tz_s_MASK   0x20
#define  sec_fab_firewall_reg_peri_fw_s_tz_s   0x54
#define  sec_fab_firewall_reg_peri_fw_s_tz_s_OFFSET 0
#define  sec_fab_firewall_reg_peri_fw_s_tz_s_MASK   0xffffffff
#define  sec_fab_firewall_reg_rom_fw_s_tz_s   0x58
#define  sec_fab_firewall_reg_rom_fw_s_tz_s_OFFSET 0
#define  sec_fab_firewall_reg_rom_fw_s_tz_s_MASK   0xffffffff
#define  sec_fab_firewall_fabFW_ROM_psmsk   0x5c
#define  sec_fab_firewall_fabFW_ROM_psmsk_OFFSET 0
#define  sec_fab_firewall_fabFW_ROM_psmsk_MASK   0xffffffff
